# Generated by Django 3.1.5 on 2021-03-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addresstouser'),
        ('orders', '0002_auto_20210310_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='accounts.addresstouser'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_product',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
