# Generated by Django 3.1.5 on 2021-03-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Category Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Product Title')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Product Slug')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Product Ingredients')),
                ('UPC', models.CharField(blank=True, max_length=12, null=True, verbose_name='Product UPC')),
                ('SKU', models.CharField(blank=True, max_length=10, null=True, verbose_name='Product SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image')),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
