# Generated by Django 3.1.5 on 2021-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Product Title')),
                ('slug', models.CharField(max_length=150, verbose_name='Product slug')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Product Ingredients')),
                ('UPC', models.CharField(blank=True, max_length=12, null=True, verbose_name='Product UPC')),
                ('SKU', models.CharField(blank=True, max_length=10, null=True, verbose_name='Product SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Image')),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
