# Generated by Django 3.1.5 on 2021-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210308_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='Product Slug'),
        ),
    ]
