# Generated by Django 3.1.5 on 2021-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210308_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Category Slug'),
        ),
    ]
